<?xml version="1.0" encoding="UTF-8"?>

<!--
File: bookTex.xml
Description:
This is a project or Document type description for a book publication to be rendered
with TeX. All file relations and processes are described in this file.

Todo:
1) Add a process section where all processes are described
2) Add file type section that describes each kind of type of file found in the component
3) Need a section to describe project folder attributes <location>
4) Need a default book project section that the system will use to start a project

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (setting | file | folder | process)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type*, value)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Files</name>
        <sectionID>Files</sectionID>
        <description>This section contains the names of all the bookTex files the RPM system will use in this projects.</description>
        <section>
            <name>Project Log File</name>
            <sectionID>projLogFile</sectionID>
            <description>The project log file.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <version>False</version>
                <value>.rpm.log</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project Error Log File</name>
            <sectionID>projErrorLogFile</sectionID>
            <description>The project error log file.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>.error.log</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Makefile File</name>
            <sectionID>makefileFile</sectionID>
            <description>Makefile file settings that may need to be changed.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>.makefile</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>

        <section>
            <name>GlobalTex TeX File</name>
            <sectionID>globalTex</sectionID>
            <description>The global contol file that feeds into the the component control file.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>global.tex</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Process</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value>*.ttf, ptx2pdf.tex, hyphenation.tex, .book.conf, global.sty</value>
            </setting>
        </section>

        <section>
            <name>BookTex TeX File</name>
            <sectionID>bookTexTex</sectionID>
            <description>The master TeX macro contol file that feeds into the the global control file.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>bookTex.tex</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Process</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>True</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>

        <section>
            <name>Hyphenation TeX File</name>
            <sectionID>hyphenationTex</sectionID>
            <description>Hyphenation file for project which is used by the renderer.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>hyphenation.tex</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Hyphenation</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value>wordlist.txt, lccode.tex</value>
            </setting>
        </section>

        <section>
            <name>Wordlist File</name>
            <sectionID>wordlistTxt</sectionID>
            <description>Wordlist for all components used in this project.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>wordlist.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Hyphenation</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value></value>
            </setting>
        </section>

        <section>
            <name>Lccode TeX File</name>
            <sectionID>lccodeTxt</sectionID>
            <description>The lccode is a text file used to declair non-word-forming characters to TeX.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of this file.</description>
                <type>string</type>
                <value>lccode.txt</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Hyphenation</value>
            </setting>
            <setting>
                <name>Version Control</name>
                <key>versionControl</key>
                <description>Is this file under version control?</description>
                <type>boolean</type>
                <value>False</value>
            </setting>
            <setting>
                <name>Dependent Files</name>
                <key>dependents</key>
                <description>The file(s) this file is dependent on.</description>
                <type>list</type>
                <value>.project.conf</value>
            </setting>
        </section>
    </section>

    <section>
        <name>Folders</name>
        <sectionID>Folders</sectionID>
        <description>This section contains the settings for all the folders needed for bookTex processing.</description>
        <section>
            <name>Project Admin Folder</name>
            <sectionID>AdminFolder</sectionID>
            <description>The project administrative folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The name of the folder that all project administrative documents will be kept.</description>
                <type>string</type>
                <value>Admin</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project Process Folder</name>
            <sectionID>ProcessFolder</sectionID>
            <description>The project process folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all processing happens.</description>
                <type>string</type>
                <value>Process</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project Hyphenation Folder</name>
            <sectionID>HyphenationFolder</sectionID>
            <description>The project hyphenation folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all hyphenation information is kept.</description>
                <type>string</type>
                <value>Hyphenation</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project Wiki Folder</name>
            <sectionID>WikiFolder</sectionID>
            <description>The project wiki notes folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all the project notes are kept.</description>
                <type>string</type>
                <value>.wiki</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project Font Folder</name>
            <sectionID>FontFolder</sectionID>
            <description>The project font folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all the project fonts are kept.</description>
                <type>string</type>
                <value>Fonts</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value></value>
            </setting>
        </section>
        <section>
            <name>Project TeX Macro Folder</name>
            <sectionID>MacroFolder</sectionID>
            <description>The project TeX macro folder.</description>
            <setting>
                <name>Name</name>
                <key>name</key>
                <description>The folder where all the TeX macros for this project are kept.</description>
                <type>string</type>
                <value>Macros</value>
            </setting>
            <setting>
                <name>Location</name>
                <key>location</key>
                <description>The location of the folder.</description>
                <type>string</type>
                <value>Process</value>
            </setting>
        </section>
    </section>
</root>

